name: GitHub Actions playwright deploy
run-name: GitHub Actions playwright deploy
on: [push]
jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'            
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Install dependencies      
        run: npm install
      - name: install playwright dependencies
        run: npx playwright install-deps chromium
      - name: Deploy
        run: railway up 
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}